export const GET_TRANSACTION_LIST = "GET_TRANSACTION_LIST"

export const GET_TRANSACTION = "GET_TRANSACTION"
export const DELETE_TRANSACTION = "DELETE_TRANSACTION"
export const ADD_TRANSACTION = "ADD_TRANSACTION"

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION"
export const GET_TRANSACTION_ITEM_LIST = "GET_TRANSACTION_ITEM_LIST"
export const ADD_TRANSACTION_ITEMS = "ADD_TRANSACTION_ITEMS"
